# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='emailid',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruiter',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
